# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c36d871ee71f164ada4ddc7ab56dd79df205b9705848c621f93d05ed65eea6a0e3e8d2c9220496130d82db133fa6e95c2992235a1afa13ddc0f0c3692c7a489

test:
  secret_key_base: 6183c8639b97ad35d7b5ac2d862c706002a8dcf98afba946e97e98dbb929cf5fefb375fd7dd34fedda24d48079e2e33ea82098d5e5b51fb02119ef05c1fdae7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
